# Adapted from https://github.com/bsmurphy/PyKrige/blob/master/appveyor.yml
build: false

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda-x64
    # not running the other tests at the moment
    # (PY3 not yet supported)
    #- PYTHON_VERSION: 3.5
    #  PYTHON_ARCH: "64"
    #  MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "cd C:\\projects\\simhash-py"
  # create a conda virtual environement and install pywin32
  # (otherwise we get a cython compilation error)
  - "conda create -n simhash-env --yes pywin32 python=%PYTHON_VERSION%"
  - activate simhash-env
  - pip install -r requirements.txt
  - python setup.py install



test_script:
  - activate simhash-env # activate the virtualenv
  - make test
